### ISSUE TITLE
Export keys on iOS does't work

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#477]
The logs show this error:

2023-02-12T12:10:04.890577 :: I :: CredentialsManager :: Restored credentials successfully ::  :: 0 ::  ::  :: 
2023-02-12T12:10:04.893670 :: E :: Main :: FlutterError: PathNotFoundException: Cannot open file, path = '/var/mobile/Containers/Data/Application/1B4212F5-8D96-4A6E-9106-9CD0286B6ADA/Library/Caches/keys6mFFsL/c-breez-credentials.json' (OS Error: No such file or directory, errno = 2) ::  :: 0 ::  :: 
PathNotFoundException: Cannot open file, path = '/var/mobile/Containers/Data/Application/1B4212F5-8D96-4A6E-9106-9CD0286B6ADA/Library/Caches/keys6mFFsL/c-breez-credentials.json' (OS Error: No such file or directory, errno = 2) :: 
	#0      _checkForErrorResponse (dart:io/common.dart:42)
	#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:364)
	#2      _rootRunUnary (dart:async/zone.dart:1406)
	<asynchronous suspension>
	#3      DevelopersView._exportKeys (package:c_breez/routes/dev/commands.dart:98)
	<asynchronous suspension>

**Comment by ubbabeck** [comment]
I did a test on the latest testflight version (6047.1). Both the deviceKey json object and the backup phrase where successfully exported in a zip file.

**Comment by roeierez** [comment]
Thanks @ubbabeck I am closing this.
